### PR TITLE
consistently return errors in JSON (fixes #757)

### LINKED ISSUE #757: mongodb errors not returned in expected json format
This is what you get when MongoDB errors -- which does not comply with our normal return format and which 'crashes' the front-end:

```
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed with error 16702: 'exception: $concat only supports strings, not NumberLong64' on server ds045089.mongolab.com:45089. The full response is { "errmsg" : "exception: $concat only supports strings, not NumberLong64", "code" : 16702, "ok" : 0.0 }
```

### PR DESCRIPTION
**Pull request by mossprescott**
Every error case now has a test that asserts that the response:
1. is in JSON format (with the right content type)
2. contains a field `error` 
3. with the expected error message

This uncovered *many* cases where errors were in plain text, or did not have a
properly formatted `error` message, or were being trapped in the wrong place,
or had an unnecessary stack trace.

Also fixed handling of parse errors in the API and the REPL (a recent
regression).

Eliminated curly quotes in responses, because they don't render right in
specs2 output.

### CODE REVIEW

**Comment by jdegoes** [comment]
This looks good and is badly needed. Two comments:

1. The errors should be standardized. Right now, some start with upper case letters, some with lower case, some have periods, some don't, some are closer to fragments, others full sentences. I suggest we adopt terse but grammatically correct one-liners with upper case first letter and periods.
2. According to HTTP 1.1, the Reason Phrase of the HTTP Status Line should be a short, human-readable, 1-line description. So we should replicate one-liners to the Reason Phrase of the HTTP Status Line.

Otherwise, looks great! Looking forward to getting this in.

**Comment by mossprescott** [comment]
OK, I'll get started. Also, this brings up an issue I thought about as I collected all these messages:

Many of the messages have a static portion, along with some piece (or sometimes, pieces) of variable information. The variable part might be the problematic path, or a detailed parse error, or a runtime error from mongo, etc. I think it would be good to use the JSON encoding to capture those variable parts as distinct values. That would make the `error` field a static, potentially recognizable message.

If we're going to put the message in the HTTP status line, I definitely think we want that to be a short, fixed text, and not a free-form description.

So I guess I'm proposing adding additional fields to the body as needed for each error. Here's a sketch:

```
404 Mount point not found.
{
  "error": "Mount point not found.",
  "errorDetail": {
    "path": "/missing/"
  }
}

400 Invalid connection URI.
{
  "error": "Invalid connection URI.",
  "errorDetail": {
    "parseError": "mongodb://localhost:8080//test"
  }
}
```

Putting the extra fields under `errorDetail` keeps them out of the top-level namespace so you can throw anything in there and not worry about collisions or confusion.

Also, as a rule I don't like echoing back information in responses that is apparent from the request. So  I will probably just remove the variable portion unless it isn't obvious (like when you give us a query and we have a problem with one reference buried in it somewhere).

One other thing: It's untypical for reason codes to be sentences or to contain punctuation, so I wonder if we're asking for trouble with that, but we can certainly try it and see if the browsers care.

**Comment by jdegoes** [comment]
> I think it would be good to use the JSON encoding to capture those variable parts as distinct values. 

Agreed.

> Putting the extra fields under errorDetail keeps them out of the top-level namespace so you can throw anything in there and not worry about collisions or confusion.

Yes, although I think we can improve on this somewhat:

```json
{
  "error": {
    "status": "Mount point not found.",
    "detail": {
      "path": "/missing/"
    }
}
```

This way there's only a single top-level property contaminating the "global" namespace.

> It's untypical for reason codes to be sentences or to contain punctuation, so I wonder if we're asking for trouble with that, but we can certainly try it and see if the browsers care.

The browsers don't care (I've done it before at previous companies). The reason phrase is accessible via `XMLHTTPRequest's` `statusText`. In fact, @garyb, Affjax does not return this at present which is something we need to rectify, as HTTP 1.1 explicitly states:

> the Reason-Phrase is intended for the human user.

**Comment by mossprescott** [comment]
This is turning into an exercise to refactor a lot of the error handling so that we can map different types of errors to the correct reason codes (whereas what we currently do most of the time is just grab the `message` field and slap that into a `BadRequest`). Not that its a bad thing, but it's going to take some time. Arg.

**Pull request merged**
