### PR TITLE
fix exception in compiler with un-annotated Expr

### LINKED ISSUE #815: support CASE statements without an ELSE clause
In continuation with the #807, "else" is not a mandatory field in CASE statement in SQL. When I query my dataset removing else, it does not return any value.

### PR DESCRIPTION
**Pull request by mossprescott**
Fixes #815.

We were trying to compile an Expr that wasn't part of the original AST, so had
no annotations. This is the easy fix: just use the LogicalPlan equivalent
directly.

Really, `attr` should be partial, so it could fail if you ask for the
annotation for some unknown node. As it is, it has to be unsafe. But really
we'd rather use fixplate probably, so I'm not going there right now.

### CODE REVIEW

**Comment by sellout** [comment]
I swear I have a stash or branch that rips out AnnotatedTree, etc. Need to find that.

(Also, yay, I’m sitting up. This is an improvement.)

**Comment by sellout** [comment]
I’ll pre-empt @jdegoes here and say “can we get an integration test for that?” 😉

Looks good, though.

**Comment by jdegoes** [comment]
> But if nobody's buying it, then I'll add a test.

Yes please! The integration test suite is in large part responsible for the quality of the backend (the finer tests help you diagnose issues but only the larger ones can ensure consistent end-to-end accuracy). Also the integration test suites are about to become even more useful when we announce our 2nd backend...

**Comment by mossprescott** [comment]
<touch>

**Pull request merged**
