### PR TITLE
various fixes related to MOVE (fixes #711)

### LINKED ISSUE #711: API: cannot move a directory
```
> use foo
switched to db foo
> show collections
Untitled\.slam.index
aabbc
bar.bazqqdasf
baz.quux
system.indexes
``` 
http://local.slamdata.com/metadata/fs//foo/foo/
```json
{
    "children": [
        {
            "name": "Untitled.slam",
            "type": "directory"
        },
        {
            "name": "aabbc",
            "type": "file"
        },
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "baz",
            "type": "directory"
        },
        {
            "name": "system",
            "type": "directory"
        }
    ]
}
```
MOVE@http://local.slamdata.com/data/fs//foo/foo/Untitled.slam/
DESTINATION: /foo/foo/U.slam/
ERROR: No file/dir at path: ./foo/Untitled.slam

### PR DESCRIPTION
**Pull request by mossprescott**
Update http4s dependency to 0.7, and update lens construction for Monocle 1.1.0.

Pass paths through as is, now that http4s preserves trailing slashes.

Treat the destination for MOVE as a directory path if the source is a
directory path.

Fix `Path.fileOf`, which was always producing a non-relative path (like
`/foo`), which makes no sense. Of course, no one was calling it.

Do something reasonable in GET /metadata with non-dir path (return 200 with
an empty object in the body).

Add a test for the error that occurs when you try to move a file on top of
an existing file.

Note: it would be great to have unit tests for the API doing the right
effects, but that's challenging given that those effects are hidden inside
Task[Unit]. I don't want to mock the filesystem statefully, so I'm settling
for testing around those effects. Perhaps we need a free algebra for
actions on the (generic) filesystem, the same way we need a free algebra
for actions on MongoDB specifically.

### CODE REVIEW

**Comment by mossprescott** [comment]
There's something funny going on with dependencies after updating to http4s 0.7:
```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.scalaz.stream:scalaz-stream_2.11:0.6a -> 0.7a
[warn] Run 'evicted' to see detailed eviction warnings
```

This is after bumping our dependency on scalaz-stream to 0.7a. I've run `evicted` and can't make any sense of the output. Nevertheless, we seem to build and run fine.

I'm open to suggestions as to how concerned we should be about this warning, and how to debug it.

**Comment by jdegoes** [comment]
>  Perhaps we need a free algebra for actions on the (generic) filesystem, the same way we need a free algebra for actions on MongoDB specifically.

Yes, for sure.

> There's something funny going on with dependencies after updating to http4s 0.7:

I'd look for other libraries that require an earlier version of scalaz-stream, or possibly look at the versions of scalaz libraries that we're using to make sure they're compatible with each other and with both scalaz-stream and http4s. What happened when you ran `evicted`?

**Comment by mossprescott** [comment]
The problem seems to be coming from http42-argonaut, so I wrote up an issue: http4s/http4s#270. Will comment here with any updates.

**Comment by jdegoes** [comment]
@mossprescott Can we merge this and deal with the warning later, or is the version mismatch potentially going to cause runtime issues?

**Comment by mossprescott** [comment]
There aren't any runtime issues as far as I can tell, so I'd say let's merge it and when we hear back from the http4s guys I can submit a fix.

**Pull request merged**
