### PR TITLE
Let the client specify if they want precise JSON.

### LINKED ISSUE #644: api: use `Accept` header to decide between strict / non-strict JSON mode

### PR DESCRIPTION
**Pull request by sellout**
Fixes #644.

This supports using any of

* application/ldjson,
* application/x-ldjson, or
* application/json;boundary=NL

as a media type, along with an optional “mode=precise” (or
“mode=readable”) extension to specify which codec to use.

The response always has a Content-Type header with the value
“application/ldjson;mode=readable” (or “precise”, if the client
requested it).

### CODE REVIEW

**Comment by jdegoes** [comment]
@mossprescott Can you get this in today? If not I'll review / merge myself.

**Comment by mossprescott** [comment]
Yes, I'm getting to it shortly.

**Comment by mossprescott** [comment]
README needs updating.

Otherwise, it looks good, not that I understand the "quality" negotiation stuff.

**Comment by sellout** [comment]
Accept headers are a bit odd … the “quality” stuff is just a preference. Default is 1.0, range is 0–1. Higher = higher preference. It’s not the only factor to take into account when sorting media types, but is is the only one we currently do.

I don’t actually expect it to be very important, which is why I didn’t bother with the more esoteric bits – it’s not like we’re a generic Web server that needs to decide between serving text/html, application/xml, and 30 other formats to generic clients.

**Pull request merged**
