### PR TITLE
Upgrade to WartRemover 0.13.

### PR DESCRIPTION
**Pull request by sellout**
The two major changes here are:

1. case classes must be final (I made case objects final, too) and
2. we can use `@SuppressWarnings` to silence the one place we use `null`
   and turn the `Null` wart back on.

Re `final case object`, I partially did it just for consistency, but
apparently there are actually ways to override objects in a subclass, so
I guess it’s useful, too.

### CODE REVIEW

**Comment by puffnfresh** [comment]
Awesome :+1:

**Comment by mossprescott** [comment]
Nice to get Null turned on. Surprised you didn't go all the way with DefaultArguments, after you changed a lot of code to remove them. Do you want to suppress those 6 occurrences and turn it on?

**Comment by sellout** [comment]
Mmm, good question … I’m on the fence with trying to remove them vs. just suppressing them. But, probably a good idea to suppress and then audit a handful of suppressions later, rather than disabling the check so we miss new occurrences.

Alright, you’ve convinced me 😉

**Comment by jdegoes** [comment]
Objects are a value, not a type, and cannot be subclassed. They do have an associated type (Foo.type), but it cannot be extended (AFAIK). So there's really no point in making objects final.

**Comment by puffnfresh** [comment]
@jdegoes objects as members can be overridden by subclasses, final is only useful there - useless for definitions in packages or other objects.

**Comment by sellout** [comment]
Right, and initially I didn’t change objects, but I saw we had a couple instances of `final case object` in the code, so I looked into it. There is a compiler option `-Yoverride-objects` that makes it possible to override an object in a subclass. EG: http://stackoverflow.com/a/26081039

Granted, our `case`s are generally in objects themselves, not in classes, so it doesn’t matter.

**Comment by sellout** [comment]
So … I should remove them, is that the consensus?

Boy, if only there were a `data` macro that centralized all the “patterns” for making subtypes behave …

**Comment by puffnfresh** [comment]
@sellout :neutral_face:

**Comment by jdegoes** [comment]
I'm OK leaving it, but clearly we would never use that abominable compiler option. :scream:

**Comment by jdegoes** [comment]
> objects as members can be overridden by subclasses, final is only useful there - useless for definitions in packages or other objects.

Yes, definitely, all members should be final except those that are necessarily inefficient implementations derived from other methods (which should probably not be implemented, actually, but that seems to be the pattern in Scalaz, anyway).

**Comment by sellout** [comment]
Hah, right? Really, the bulk of my motivation was just a more consistent appearance across all the cases. *shrug* (Why is there no emoji or GitHub icon for that?!)

**Comment by mossprescott** [comment]
So, everyone's OK with merging this then?

@sellout: are you going to enable DefaultArguments?

**Comment by jdegoes** [comment]
It's up to you guys, I don't think that WartRemover will be maintained very well in the presence of Typesafe's alternative (plus the ScalaTest folks are trying something similar, I think). But if it's useful / fast for now, then :+1: .

**Comment by sellout** [comment]
Yeah, hopefully we just improve code using WR, then swap in whatever TS or ST come up with when it’s ready.

Ready to merge once tests pass …

**Comment by jdegoes** [comment]
@sellout Conflicts.

**Pull request merged**
