### PR TITLE
[SD-946] Fix regression where backend not updated when config changed

### PR DESCRIPTION
**Pull request by wemrysi**
This fixes the regression introduced in #910 where the backend isn't updated when the config changes. It also includes tests that should prevent this regression in the future.

### CODE REVIEW

**Comment by jdegoes** [comment]
@wemrysi Don't forget to nominate a reviewer or this will get stuck in the queue. :smile:

**Comment by wemrysi** [comment]
@jdegoes Thanks for the reminder, assigned to @mossprescott mostly for continuity with #910. @jedesah you may want to take a look as well given your recent work on these tests.

**Comment by mossprescott** [comment]
So I like this approach, which is to make the backend, along with the config, part of the state in FileSystemApi, while keeping them both pure values. Eventually, they will be unified and this approach will still work.

Aside from the formatting issues, I'm ready to merge this.

**Comment by wemrysi** [comment]
Ok, cleaned up the formatting and removed the unused test helper.

**Comment by jonsterling** [comment]
thank the ʟoʀᴅ this is merged! ;-)

**Pull request merged**
